spring.application.name=backend

# Config PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/MovieTheater
spring.datasource.username=postgres
spring.datasource.password=123sql
spring.datasource.driver-class-name=org.postgresql.Driver

# Config JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.web.resources.add-mappings=false
spring.jackson.serialization.write-dates-as-timestamps=false

# src/main/resources/application.properties
upload.path=images


spring.cache.cache-names=bookingInfo
spring.cache.caffeine.spec=expireAfterWrite=16m

#Vnpay codes
vnpay.tmnCode =
vnpay.hashSecret =
vnpay.payUrl =
vnpay.returnUrl =

# Spring Security
# spring.security.user.name=admin
# spring.security.user.password=secretadmin

# springdoc.api-docs.enabled=true
# springdoc.swagger-ui.enabled=true


